param(
    [string]$CsvPath = 'Database\ability_parity\csv\gamedata\abilities.csv',
    [string]$MySqlExePath = 'C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe',
    [string]$MySqlHost = '127.0.0.1',
    [int]$MySqlPort = 3306,
    [string]$MySqlUser = 'root',
    [string]$MySqlPassword = 'password',
    [string]$WorldSchema = 'war_world_curated',
    [string]$OutputSql = 'Database\ability_parity\work\abilities_csv_sync.generated.sql',
    [switch]$Apply
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'

function Resolve-ProjectPath {
    param([Parameter(Mandatory = $true)][string]$PathValue)

    if ([string]::IsNullOrWhiteSpace($PathValue))
        { throw "Path cannot be empty." }

    if ([System.IO.Path]::IsPathRooted($PathValue))
        { return [System.IO.Path]::GetFullPath($PathValue) }

    return [System.IO.Path]::GetFullPath((Join-Path (Get-Location).Path $PathValue))
}

function Invoke-MySqlFile {
    param(
        [Parameter(Mandatory = $true)][string]$ExecutablePath,
        [Parameter(Mandatory = $true)][string]$Server,
        [Parameter(Mandatory = $true)][int]$Port,
        [Parameter(Mandatory = $true)][string]$User,
        [Parameter(Mandatory = $true)][string]$Password,
        [Parameter(Mandatory = $true)][string]$FilePath
    )

    $command = "set MYSQL_PWD=$Password&&`"$ExecutablePath`" --host=$Server --port=$Port --user=$User < `"$FilePath`""
    $result = cmd /c $command 2>&1
    if ($LASTEXITCODE -ne 0)
    {
        throw "mysql file import failed: $FilePath`n$result"
    }
}

function SqlString {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value)
        { return 'NULL' }

    return "'" + $Value.Replace("'", "''") + "'"
}

$resolvedCsvPath = Resolve-ProjectPath -PathValue $CsvPath
$resolvedMySqlExe = Resolve-ProjectPath -PathValue $MySqlExePath
$resolvedOutputSql = Resolve-ProjectPath -PathValue $OutputSql

if (-not (Test-Path -LiteralPath $resolvedCsvPath))
    { throw "abilities.csv not found: $resolvedCsvPath" }
if (-not (Test-Path -LiteralPath $resolvedMySqlExe))
    { throw "mysql executable not found: $resolvedMySqlExe" }

Add-Type -AssemblyName Microsoft.VisualBasic

$rows = New-Object 'System.Collections.Generic.Dictionary[int,object]'
$stats = [ordered]@{
    csv_numeric_rows = 0
    parsed_rows = 0
}

$parser = New-Object Microsoft.VisualBasic.FileIO.TextFieldParser($resolvedCsvPath)
$parser.SetDelimiters(',')
$parser.HasFieldsEnclosedInQuotes = $true
[void]$parser.ReadFields()
[void]$parser.ReadFields()

while (-not $parser.EndOfData)
{
    $row = $parser.ReadFields()
    if ($null -eq $row -or $row.Length -lt 9)
        { continue }

    $idText = if ($row.Length -gt 0 -and $null -ne $row[0]) { [string]$row[0] } else { '' }
    $idText = $idText.Trim()
    if ($idText -notmatch '^\d+$')
        { continue }

    $stats.csv_numeric_rows++

    $entry = [int]$idText
    if ($entry -le 0 -or $entry -gt [UInt16]::MaxValue)
        { continue }

    $name = if ($row.Length -gt 1 -and $null -ne $row[1]) { [string]$row[1] } else { '' }
    $name = $name.Trim()
    if ($name.Length -gt 255)
        { $name = $name.Substring(0, 255) }

    $icon = 0
    $iconText = if ($row.Length -gt 4 -and $null -ne $row[4]) { [string]$row[4] } else { '' }
    $iconText = $iconText.Trim()
    if ($iconText -match '^-?\d+(\.\d+)?$')
    {
        $icon = [int][double]$iconText
        if ($icon -lt 0) { $icon = 0 }
        if ($icon -gt [UInt16]::MaxValue) { $icon = [UInt16]::MaxValue }
    }

    $effect = 0
    $effectText = if ($row.Length -gt 8 -and $null -ne $row[8]) { [string]$row[8] } else { '' }
    $effectText = $effectText.Trim()
    if ($effectText -match '^-?\d+(\.\d+)?$')
    {
        $effect = [int][double]$effectText
        if ($effect -lt 0) { $effect = 0 }
        if ($effect -gt [UInt16]::MaxValue) { $effect = [UInt16]::MaxValue }
    }

    $rows[$entry] = [pscustomobject]@{
        Entry = [UInt16]$entry
        Name = $name
        IconId = [UInt16]$icon
        EffectID = [UInt16]$effect
    }
}

$parser.Close()
$stats.parsed_rows = $rows.Count

$orderedRows = @(
    $rows.GetEnumerator() | Sort-Object -Property Name | ForEach-Object { $_.Value }
)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('-- Generated by Database/ability_parity/Sync-AbilitiesFromCsv.ps1')
[void]$sb.AppendLine("-- Source CSV: $resolvedCsvPath")
[void]$sb.AppendLine("-- Parsed rows: $($stats.parsed_rows)")
[void]$sb.AppendLine()
[void]$sb.AppendLine("USE $WorldSchema;")
[void]$sb.AppendLine('START TRANSACTION;')

if ($orderedRows.Count -gt 0)
{
    [void]$sb.AppendLine('INSERT INTO `abilities` (`Entry`,`Name`,`IconId`,`EffectID`) VALUES')

    for ($i = 0; $i -lt $orderedRows.Count; $i++)
    {
        $row = $orderedRows[$i]
        $suffix = if ($i -lt $orderedRows.Count - 1) { ',' } else { '' }
        [void]$sb.AppendLine(
            "($($row.Entry),$(SqlString $row.Name),$($row.IconId),$($row.EffectID))$suffix"
        )
    }

    [void]$sb.AppendLine('ON DUPLICATE KEY UPDATE')
    [void]$sb.AppendLine('`Name`=VALUES(`Name`),')
    [void]$sb.AppendLine('`IconId`=VALUES(`IconId`),')
    [void]$sb.AppendLine('`EffectID`=VALUES(`EffectID`);')
}

[void]$sb.AppendLine('COMMIT;')

$outputDir = Split-Path -Path $resolvedOutputSql -Parent
if (-not [string]::IsNullOrWhiteSpace($outputDir))
{
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

[System.IO.File]::WriteAllText($resolvedOutputSql, $sb.ToString(), [System.Text.Encoding]::UTF8)

Write-Host "Wrote CSV sync SQL: $resolvedOutputSql"
Write-Host "Stats:"
$stats.GetEnumerator() | ForEach-Object { Write-Host ("  {0} = {1}" -f $_.Key, $_.Value) }

if ($Apply)
{
    Write-Host "Applying CSV sync SQL to $WorldSchema..."
    Invoke-MySqlFile -ExecutablePath $resolvedMySqlExe -Server $MySqlHost -Port $MySqlPort -User $MySqlUser -Password $MySqlPassword -FilePath $resolvedOutputSql
    Write-Host "Apply completed."
}
