param(
    [string]$ToolkitSqlDir = 'C:\Users\Admin\source\repos\Shmerrick\WAR-RE-Toolkit\Database Tables\Londos Server v2',
    [string]$SchemaSqlPath = 'Database\ability_parity\mythic_bin.schema.sql',
    [string]$OutputSql = 'Database\ability_parity\work\mythic_bin_sync.generated.sql',
    [string]$MySqlExePath = 'C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe',
    [string]$MySqlHost = '127.0.0.1',
    [int]$MySqlPort = 3306,
    [string]$MySqlUser = 'root',
    [string]$MySqlPassword = 'password',
    [string]$LondoSchema = 'War',
    [string]$WorldSchema = 'war_world_curated',
    [switch]$Apply,
    [switch]$SkipLondoImport
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'

function Resolve-ProjectPath {
    param([Parameter(Mandatory = $true)][string]$PathValue)

    if ([string]::IsNullOrWhiteSpace($PathValue))
        { throw "Path cannot be empty." }

    if ([System.IO.Path]::IsPathRooted($PathValue))
        { return [System.IO.Path]::GetFullPath($PathValue) }

    return [System.IO.Path]::GetFullPath((Join-Path (Get-Location).Path $PathValue))
}

function Invoke-MySqlFile {
    param(
        [Parameter(Mandatory = $true)][string]$ExecutablePath,
        [Parameter(Mandatory = $true)][string]$Server,
        [Parameter(Mandatory = $true)][int]$Port,
        [Parameter(Mandatory = $true)][string]$User,
        [Parameter(Mandatory = $true)][string]$Password,
        [Parameter(Mandatory = $true)][string]$FilePath
    )

    $command = "set MYSQL_PWD=$Password&&`"$ExecutablePath`" --host=$Server --port=$Port --user=$User < `"$FilePath`""
    $result = cmd /c $command 2>&1
    if ($LASTEXITCODE -ne 0)
    {
        throw "mysql file import failed: $FilePath`n$result"
    }
}

$londoFiles = @(
    'War_Ability.sql',
    'War_AbilityBin.sql',
    'War_AbilityComponentBin.sql',
    'War_AbilityComponentXComponent.sql',
    'War_AbilityExpression.sql',
    'War_AbilityRequirmentBin.sql',
    'War_AbilityUpgradeBin.sql',
    'War_AbilityUpgradeEntry.sql',
    'War_ItemAbility.sql'
)

$resolvedToolkitSqlDir = Resolve-ProjectPath -PathValue $ToolkitSqlDir
$resolvedSchemaSqlPath = Resolve-ProjectPath -PathValue $SchemaSqlPath
$resolvedOutputSql = Resolve-ProjectPath -PathValue $OutputSql
$resolvedMySqlExe = Resolve-ProjectPath -PathValue $MySqlExePath

if (-not (Test-Path -LiteralPath $resolvedToolkitSqlDir))
    { throw "ToolkitSqlDir not found: $resolvedToolkitSqlDir" }
if (-not (Test-Path -LiteralPath $resolvedSchemaSqlPath))
    { throw "mythic_bin schema SQL not found: $resolvedSchemaSqlPath" }
if (-not (Test-Path -LiteralPath $resolvedMySqlExe))
    { throw "mysql executable not found: $resolvedMySqlExe" }

foreach ($fileName in $londoFiles)
{
    $path = Join-Path $resolvedToolkitSqlDir $fileName
    if (-not (Test-Path -LiteralPath $path))
        { throw "Required Londo SQL dump not found: $path" }
}

$outputDir = Split-Path -Path $resolvedOutputSql -Parent
if (-not [string]::IsNullOrWhiteSpace($outputDir))
{
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$schemaSql = Get-Content -LiteralPath $resolvedSchemaSqlPath -Raw
$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine('-- Generated by Database/ability_parity/Sync-LondoAbilityGraph.ps1')
[void]$sb.AppendLine("-- Londo source schema: $LondoSchema")
[void]$sb.AppendLine("-- Target world schema: $WorldSchema")
[void]$sb.AppendLine('SET FOREIGN_KEY_CHECKS = 0;')
[void]$sb.AppendLine("USE ``$WorldSchema``;")
[void]$sb.AppendLine()
[void]$sb.AppendLine($schemaSql.TrimEnd())
[void]$sb.AppendLine()
[void]$sb.AppendLine('TRUNCATE TABLE mythic_bin_itemability;')
[void]$sb.AppendLine('TRUNCATE TABLE mythic_bin_abilityupgradeentry;')
[void]$sb.AppendLine('TRUNCATE TABLE mythic_bin_abilityupgradebin;')
[void]$sb.AppendLine('TRUNCATE TABLE mythic_bin_abilityexpression;')
[void]$sb.AppendLine('TRUNCATE TABLE mythic_bin_abilitycomponentlink;')
[void]$sb.AppendLine('TRUNCATE TABLE mythic_bin_abilitycomponentbin;')
[void]$sb.AppendLine('TRUNCATE TABLE mythic_bin_abilitybin;')
[void]$sb.AppendLine('TRUNCATE TABLE mythic_bin_abilityrequirmentbin;')
[void]$sb.AppendLine('TRUNCATE TABLE mythic_bin_ability;')
[void]$sb.AppendLine()

[void]$sb.AppendLine("INSERT INTO mythic_bin_ability (")
[void]$sb.AppendLine("  ID,Name,Description,EffectID,MinLevel,IsBuff,IsDebuff,IsDamaging,IsHealing,IsGranted,IsPassive,IsOffensive,")
[void]$sb.AppendLine("  Flags,Casttime,Cooldown,AP,Specialization,ChannelInterval,TacticType,``Range``,MoraleLevel,MoraleCost,CastType,SpellDamageType,")
[void]$sb.AppendLine("  TargetType,MaxTargets,MythicComponentData,ComponentData,RequirmentsData,ComponentDataValues,ComponentTriggers,FlagBits")
[void]$sb.AppendLine(")")
[void]$sb.AppendLine("SELECT")
[void]$sb.AppendLine("  ID,Name,Description,EffectID,MinLevel,IsBuff,IsDebuff,IsDamaging,IsHealing,IsGranted,IsPassive,IsOffensive,")
[void]$sb.AppendLine("  Flags,Casttime,Cooldown,AP,Specialization,ChannelInterval,TacticType,``Range``,MoraleLevel,MoraleCost,CastType,SpellDamageType,")
[void]$sb.AppendLine("  TargetType,MaxTargets,MythicComponentData,ComponentData,RequirmentsData,ComponentDataValues,ComponentTriggers,FlagBits")
[void]$sb.AppendLine("FROM ``$LondoSchema``.``Ability``;")
[void]$sb.AppendLine()

[void]$sb.AppendLine("INSERT INTO mythic_bin_abilitybin (ID,EffectID,MinLevel,TargetType,``Range``,AP,Castime,Cooldown)")
[void]$sb.AppendLine("SELECT ID,EffectID,MinLevel,TargetType,``Range``,AP,Castime,Cooldown")
[void]$sb.AppendLine("FROM ``$LondoSchema``.``AbilityBin``;")
[void]$sb.AppendLine()

[void]$sb.AppendLine("INSERT INTO mythic_bin_abilitycomponentbin (ID,A00,``Values``,Multipliers,ActivationDelay,Duration,Flags,``Interval``,Radius,ConeAngle,FlightSpeed,MaxTargets,Description)")
[void]$sb.AppendLine("SELECT ID,A00,``Values``,Multipliers,ActivationDelay,Duration,Flags,``Interval``,Radius,ConeAngle,FlightSpeed,MaxTargets,Description")
[void]$sb.AppendLine("FROM ``$LondoSchema``.``AbilityComponentBin``;")
[void]$sb.AppendLine()

[void]$sb.AppendLine("INSERT INTO mythic_bin_abilitycomponentlink (ID,AbilityID,ComponentID,``Trigger``,VfxID,``Index``,Disabled)")
[void]$sb.AppendLine("SELECT ID,AbilityID,ComponentID,``Trigger``,VfxID,``Index``,Disabled")
[void]$sb.AppendLine("FROM ``$LondoSchema``.``AbilityComponentXComponent``;")
[void]$sb.AppendLine()

[void]$sb.AppendLine("INSERT INTO mythic_bin_abilityexpression (ID,AbilityID,ComponentID,``Index``,``Type``,Operation,``Condition``,LogicOperator,RequirmentID,Disabled)")
[void]$sb.AppendLine("SELECT ID,AbilityID,ComponentID,``Index``,``Type``,Operation,``Condition``,LogicOperator,RequirmentID,Disabled")
[void]$sb.AppendLine("FROM ``$LondoSchema``.``AbilityExpression``;")
[void]$sb.AppendLine()

[void]$sb.AppendLine("INSERT INTO mythic_bin_abilityrequirmentbin (ID,``Name``,Disabled)")
[void]$sb.AppendLine("SELECT ID,``Name``,Disabled")
[void]$sb.AppendLine("FROM ``$LondoSchema``.``AbilityRequirmentBin``;")
[void]$sb.AppendLine()

[void]$sb.AppendLine("INSERT INTO mythic_bin_abilityupgradebin (ID,UpgradeID)")
[void]$sb.AppendLine("SELECT ID,UpgradeID")
[void]$sb.AppendLine("FROM ``$LondoSchema``.``AbilityUpgradeBin``;")
[void]$sb.AppendLine()

[void]$sb.AppendLine("INSERT INTO mythic_bin_abilityupgradeentry (ID,AbilityUpgradeBinID,``Index``,V1,V2,V3,V4,V5,V6,V7,V8,``Values``)")
[void]$sb.AppendLine("SELECT ID,AbilityUpgradeBinID,``Index``,V1,V2,V3,V4,V5,V6,V7,V8,``Values``")
[void]$sb.AppendLine("FROM ``$LondoSchema``.``AbilityUpgradeEntry``;")
[void]$sb.AppendLine()

[void]$sb.AppendLine("INSERT INTO mythic_bin_itemability (ID,AbilityID,ItemID,``Time``,Unk1,Cooldown)")
[void]$sb.AppendLine("SELECT ID,AbilityID,ItemID,``Time``,Unk1,Cooldown")
[void]$sb.AppendLine("FROM ``$LondoSchema``.``ItemAbility``;")
[void]$sb.AppendLine()

[void]$sb.AppendLine("SELECT 'mythic_bin_ability' AS TableName, COUNT(*) AS RowCount FROM mythic_bin_ability")
[void]$sb.AppendLine("UNION ALL SELECT 'mythic_bin_abilitybin', COUNT(*) FROM mythic_bin_abilitybin")
[void]$sb.AppendLine("UNION ALL SELECT 'mythic_bin_abilitycomponentbin', COUNT(*) FROM mythic_bin_abilitycomponentbin")
[void]$sb.AppendLine("UNION ALL SELECT 'mythic_bin_abilitycomponentlink', COUNT(*) FROM mythic_bin_abilitycomponentlink")
[void]$sb.AppendLine("UNION ALL SELECT 'mythic_bin_abilityexpression', COUNT(*) FROM mythic_bin_abilityexpression")
[void]$sb.AppendLine("UNION ALL SELECT 'mythic_bin_abilityrequirmentbin', COUNT(*) FROM mythic_bin_abilityrequirmentbin")
[void]$sb.AppendLine("UNION ALL SELECT 'mythic_bin_abilityupgradebin', COUNT(*) FROM mythic_bin_abilityupgradebin")
[void]$sb.AppendLine("UNION ALL SELECT 'mythic_bin_abilityupgradeentry', COUNT(*) FROM mythic_bin_abilityupgradeentry")
[void]$sb.AppendLine("UNION ALL SELECT 'mythic_bin_itemability', COUNT(*) FROM mythic_bin_itemability;")
[void]$sb.AppendLine("SET FOREIGN_KEY_CHECKS = 1;")

[System.IO.File]::WriteAllText($resolvedOutputSql, $sb.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "Wrote Mythic graph sync SQL: $resolvedOutputSql"

if ($Apply)
{
    if (-not $SkipLondoImport)
    {
        foreach ($fileName in $londoFiles)
        {
            $filePath = Join-Path $resolvedToolkitSqlDir $fileName
            Write-Host "Importing Londo dump: $fileName"
            Invoke-MySqlFile -ExecutablePath $resolvedMySqlExe -Server $MySqlHost -Port $MySqlPort -User $MySqlUser -Password $MySqlPassword -FilePath $filePath
        }
    }
    else
    {
        Write-Host "Skipping Londo dump import (-SkipLondoImport set)."
    }

    Write-Host "Applying Mythic graph sync SQL to $WorldSchema..."
    Invoke-MySqlFile -ExecutablePath $resolvedMySqlExe -Server $MySqlHost -Port $MySqlPort -User $MySqlUser -Password $MySqlPassword -FilePath $resolvedOutputSql
    Write-Host "Apply completed."
}
